### PR TITLE
Alation Quickstart - Resubmission

### PR DESCRIPTION
**Pull request by nickjewell-alation**
Updated quickstart to include:

New left-hand navigation

New screenshots for starting Alation Trial within Partner Connect

Refreshed content throughout

New content for Data Quality within Alation

Ready for Snowflake Summit 24!

(Also: removed file: package-lock.json to avoid conflicts )

### CODE REVIEW

**Comment by iamontheinet** [comment]
@vinodhini-sd @nickjewell-alation When running the site locally, I am getting these errors...

`err	getting_started_with_alation/getting_started_with_alation.md ./assets/Screen8-Optional-Apps1.png => : open /Users/ddesai/Apps/sfquickstarts/site/sfguides/src/getting_started_with_alation/assets/Screen8-Optional-Apps1.png: no such file or directory
./assets/Screen8-Optional-Apps2.png => : open /Users/ddesai/Apps/sfquickstarts/site/sfguides/src/getting_started_with_alation/assets/Screen8-Optional-Apps2.png: no such file or directory
./assets/Screen8-Optional-Apps3.png => : open /Users/ddesai/Apps/sfquickstarts/site/sfguides/src/getting_started_with_alation/assets/Screen8-Optional-Apps3.png: no such file or directory
./assets/Screen8-Optional-Apps4.png => : open /Users/ddesai/Apps/sfquickstarts/site/sfguides/src/getting_started_with_alation/assets/Screen8-Optional-Apps4.png: no such file or directory
./assets/Screen8-Optional-Apps5.png => : open /Users/ddesai/Apps/sfquickstarts/site/sfguides/src/getting_started_with_alation/assets/Screen8-Optional-Apps5.png: no such file or directory
./assets/Screen8-Optional-Apps6.png => : open /Users/ddesai/Apps/sfquickstarts/site/sfguides/src/getting_started_with_alation/assets/Screen8-Optional-Apps6.png: no such file or directory
./assets/Screen8-Optional-Apps7.png => : open /Users/ddesai/Apps/sfquickstarts/site/sfguides/src/getting_started_with_alation/assets/Screen8-Optional-Apps7.png: no such file or directory
./assets/Screen8-Optional-Apps8.png => : open /Users/ddesai/Apps/sfquickstarts/site/sfguides/src/getting_started_with_alation/assets/Screen8-Optional-Apps8.png: no such file or directory
./assets/Screen8-Optional-Apps9.png => : open /Users/ddesai/Apps/sfquickstarts/site/sfguides/src/getting_started_with_alation/assets/Screen8-Optional-Apps9.png: no such file or directory
./assets/Screen8-Optional-Apps10.png => : open /Users/ddesai/Apps/sfquickstarts/site/sfguides/src/getting_started_with_alation/assets/Screen8-Optional-Apps10.png: no such file or directory
./assets/Screen8-Optional-Apps11.png => : open /Users/ddesai/Apps/sfquickstarts/site/sfguides/src/getting_started_with_alation/assets/Screen8-Optional-Apps11.png: no such file or directory
./assets/Screen8-Optional-Apps12.png => : open /Users/ddesai/Apps/sfquickstarts/site/sfguides/src/getting_started_with_alation/assets/Screen8-Optional-Apps12.png: no such file or directory`

**Comment by nickjewell-alation** [comment]
Markdown file updated - removed orphaned links to missing images. Should be good to go?

**Comment by dataguyatalation** [comment]
> @vinodhini-sd @nickjewell-alation When running the site locally, I am getting these errors...
> 
> `err getting_started_with_alation/getting_started_with_alation.md ./assets/Screen8-Optional-Apps1.png => : open /Users/ddesai/Apps/sfquickstarts/site/sfguides/src/getting_started_with_alation/assets/Screen8-Optional-Apps1.png: no such file or directory ./assets/Screen8-Optional-Apps2.png => : open /Users/ddesai/Apps/sfquickstarts/site/sfguides/src/getting_started_with_alation/assets/Screen8-Optional-Apps2.png: no such file or directory ./assets/Screen8-Optional-Apps3.png => : open /Users/ddesai/Apps/sfquickstarts/site/sfguides/src/getting_started_with_alation/assets/Screen8-Optional-Apps3.png: no such file or directory ./assets/Screen8-Optional-Apps4.png => : open /Users/ddesai/Apps/sfquickstarts/site/sfguides/src/getting_started_with_alation/assets/Screen8-Optional-Apps4.png: no such file or directory ./assets/Screen8-Optional-Apps5.png => : open /Users/ddesai/Apps/sfquickstarts/site/sfguides/src/getting_started_with_alation/assets/Screen8-Optional-Apps5.png: no such file or directory ./assets/Screen8-Optional-Apps6.png => : open /Users/ddesai/Apps/sfquickstarts/site/sfguides/src/getting_started_with_alation/assets/Screen8-Optional-Apps6.png: no such file or directory ./assets/Screen8-Optional-Apps7.png => : open /Users/ddesai/Apps/sfquickstarts/site/sfguides/src/getting_started_with_alation/assets/Screen8-Optional-Apps7.png: no such file or directory ./assets/Screen8-Optional-Apps8.png => : open /Users/ddesai/Apps/sfquickstarts/site/sfguides/src/getting_started_with_alation/assets/Screen8-Optional-Apps8.png: no such file or directory ./assets/Screen8-Optional-Apps9.png => : open /Users/ddesai/Apps/sfquickstarts/site/sfguides/src/getting_started_with_alation/assets/Screen8-Optional-Apps9.png: no such file or directory ./assets/Screen8-Optional-Apps10.png => : open /Users/ddesai/Apps/sfquickstarts/site/sfguides/src/getting_started_with_alation/assets/Screen8-Optional-Apps10.png: no such file or directory ./assets/Screen8-Optional-Apps11.png => : open /Users/ddesai/Apps/sfquickstarts/site/sfguides/src/getting_started_with_alation/assets/Screen8-Optional-Apps11.png: no such file or directory ./assets/Screen8-Optional-Apps12.png => : open /Users/ddesai/Apps/sfquickstarts/site/sfguides/src/getting_started_with_alation/assets/Screen8-Optional-Apps12.png: no such file or directory`

https://github.com/iamontheinet - Those are part of the old version when you look at the diff for the md file. They are not currently in the new version. Did the code not merge correctly?
Thanks!

**Comment by dataguyatalation** [comment]
Nick informed me he pushed the md file again and that is why the diff looks correct.

**Pull request merged**
