### PR TITLE
sigma-google_analytics_4_template_setup

### PR DESCRIPTION
**Pull request by pballai**
I accept the Snowflake CLA.

### CODE REVIEW

**Comment by sfc-gh-lambrosetti** [comment]
Hi @pballai - thanks for submitting! a few changes requested:

- please remove the footer image
- in "Transforming the Raw GA4 Data" please provide any SQL code as a Snowflake notebook and/or as a code block in the quickstart, do not link to download SQL from an external link
- please make sure you follow our guide on creating quickstarts: 

```
Always check if the first step is labeled Overview AND then make sure there are these specific sections under that step: 1) Overview, 2) What You Will Build, 3) What You Will Learn, 4) Prerequisites

Always check if the last step is labeled Conclusion and Resources and then make sure it includes these specific sections **1) Conclusion, 2) What You Learned, and 3) Resources (with links to docs, blogs, videos, etc.)```

Specifically, the last section needs to be labeled "Conclusion and Resources" with the sections as well (some of which you already have!)

**Comment by iamontheinet** [comment]
@pballai 

- Remove '#' in front of the title
- Resolve conflicts. FYI, you should not be modifying or committing package.json.

cc @lukegalbraithrussell

**Comment by pballai** [comment]
Both tasks are completed.

Phil Ballai
Enterprise Architect
 [image: Sigma] <https://www.sigmacomputing.com/>
908.528.4920
Raleigh, NC
sigmacomputing.com <https://www.sigmacomputing.com/>

**Comment by pballai** [comment]
Please disregard and close this PR. It is replaced with this one:
https://github.com/Snowflake-Labs/sfquickstarts/pull/1671

**Pull request closed without merging**
