### PR TITLE
IBM DataStage Load Snowflake Lab Guide Initial PR

### PR DESCRIPTION
**Pull request by shreya-sisodia**
Hello there, first time contributor of a Quickstart. This lab guide is for IBM DataStage to load data into Snowflake. Please let me know if any updates are needed. Thank you!

### CODE REVIEW

**Comment by shreya-sisodia** [comment]
@jdanielmyers Great to meet you! This is my first time contributing, we double and triple checked the instructions, but please let us know if there's anything you'd like us to update. Thanks!

**Comment by iamontheinet** [comment]
@shreya-sisodia Thank you for your contribution. Overall the QS looks great. Can you please incorporate the following edits?

- Under "Prerequisites" please provide links for creating trial accounts for both IBM CP4DaaS and Snowflake
- Remove "This tutorial takes approximately 20 minutes to complete." since we already display the duration as part of the QS and each step.
- None of the images under "Check your progress" are being displayed. Please make sure they are included in the PR and being displayed as expected.

Thanks again!

**Comment by shreya-sisodia** [comment]
@iamontheinet Hi there! Thank you for the feedback - I've incorporated the changes and resubmitted.

**Comment by shreya-sisodia** [comment]
Hi - I'm opening a new PR with the feedback incorporated. #619

**Pull request closed without merging**
