### PR TITLE
Titanic Edits and Cortex ML guide created

### PR DESCRIPTION
**Pull request by aefendic**
Hex Summit '24 HOL updates made in relation to [#1208](https://github.com/Snowflake-Labs/sfquickstarts/pull/1208)
 
Additionally, a net new Cortex Quickstart Guide is created. Note, the Related Resources Section of the Cortex Quickstart Guide are yet to be added as the related assets have not yet been published. These are to be added as soon as the assets go live.

### CODE REVIEW

**Comment by aefendic** [comment]
Please see this [loom](https://www.loom.com/share/4e81bf3487614d22ab874d3faadc1b24?sid=6c55e2c4-bda6-42ec-989a-a94338288bf7) for an easier review!

cc: @iamontheinet

**Comment by iamontheinet** [comment]
@aefendic When I try to checkout this PR and serve the site locally I am getting this error...

```sh
err	hex_cortex/cortex.md assets/connection_toggles.png => : open /Users/ddesai/Apps/sfquickstarts/site/sfguides/src/hex_cortex/assets/connection_toggles.png: no such file or directory
assets/import_connection.png => : open /Users/ddesai/Apps/sfquickstarts/site/sfguides/src/hex_cortex/assets/import_connection.png: no such file or directory
assets/edit_connection.png => : open /Users/ddesai/Apps/sfquickstarts/site/sfguides/src/hex_cortex/assets/edit_connection.png: no such file or directory
```

**Comment by aefendic** [comment]
@iamontheinet files added, please try again

**Comment by iamontheinet** [comment]
@aefendic Getting this error...

`err	hex_cortex/cortex.md assets/connection_toggles.png => : open /Users/ddesai/Apps/sfquickstarts/site/sfguides/src/hex_cortex/assets/connection_toggles.png: no such file or directory`

Does it work for you locally?

**Comment by aefendic** [comment]
@iamontheinet it does... 
that is strange. It must be finding those files from another branch I am working on? That would be my only guess

**Pull request merged**
