### PR TITLE
Rudder stack quickstart

### PR DESCRIPTION
**Pull request by MattKelliher-Gibson**
Submitting a new guide for approval

### CODE REVIEW

**Comment by sfc-gh-lambrosetti** [comment]
Snowflake team, if there are any questions before merging, please let me know. RudderStack team is the main author, but I provided guidance on assets.

**Comment by iamontheinet** [comment]
Hi @MattKelliher-Gibson! Thank you for your contribution. Overall the QS Guide looks great. Can you please make the following edits and submit a new PR?

1. The first "Overview" step should include these sections **Overview, What You Will Learn, What You Will Build and Prerequisite**s 
2. The last "Conclusion" step should include these sections **What You Learned and Related Resources**

You can use this QS as a reference -- [https://quickstarts.snowflake.com/guide/getting_started_with_dataengineering_ml_using_snowpark_python/index.html](https://quickstarts.snowflake.com/guide/getting_started_with_dataengineering_ml_using_snowpark_python/index.html)

Hope that helps.

Cheers,
Dash

cc @sfc-gh-lambrosetti

**Comment by MattKelliher-Gibson** [comment]
@iamontheinet Thanks for the feedback. One question, in your comment you asked for a section on What You Will Build. The example given doesn't have that section, how is it different from What You Will Learn?

**Comment by iamontheinet** [comment]
> @iamontheinet Thanks for the feedback. One question, in your comment you asked for a section on What You Will Build. The example given doesn't have that section, how is it different from What You Will Learn?

Hi @MattKelliher-Gibson! That section is optional if you're not actually building an app, data pipeline, etc. of some sort. See this QS -- [https://quickstarts.snowflake.com/guide/image_recognition_snowpark_pytorch_streamlit_openai/index.html](https://quickstarts.snowflake.com/guide/image_recognition_snowpark_pytorch_streamlit_openai/index.html)

**Comment by MattKelliher-Gibson** [comment]
@iamontheinet  I have added a commit with the updates you asked for. If anything else is missing or needs changing, please let me know.

CC: @sfc-gh-lambrosetti

**Comment by iamontheinet** [comment]
> @iamontheinet I have added a commit with the updates you asked for. If anything else is missing or needs changing, please let me know.
> 
> CC: @sfc-gh-lambrosetti

Thanks @MattKelliher-Gibson! Will review, merge, and deploy it soon.

**Pull request merged**
