### PR TITLE
Add guide: getting started with SnowDDL

### PR DESCRIPTION
**Pull request by littleK0i**
This guide explains how to get started with SnowDDL object management tool.

GitHub: https://github.com/littleK0i/SnowDDL
Docs: https://docs.snowddl.com/

Thank you!

### CODE REVIEW

**Comment by littleK0i** [comment]
Is there anything blocking this page from being merged? I am happy to fix it.

Thank you.

**Comment by littleK0i** [comment]
I agree to the Snowflake CLA 👍

**Comment by jdanielmyers** [comment]
Hey! Thank you for agreeing to the CLA! 

I notice that this is called snowddl - can you please rename this so that it does not use "snow" in the name? We try to keep "snow" named things for official product names 👍

**Comment by littleK0i** [comment]
Hi @jdanielmyers ,

Thank you for noticing this pull request.

I think it might be worth mentioning "snow" prefix being reserved for official products somewhere in guidelines. Otherwise more developers will use it naturally for future projects.

Renaming "snowddl" is not an easy task at this point, since we already have a lot of stuff in place:

- domain with documentation: https://docs.snowddl.com/ ;
- PyPi package `snowddl` with other packages depending on it;
- a few articles referring to `SnowDDL` name;
- Google acknowledged that `snowddl` is a valid search topic, not a misspelled word (takes a few months);

In my opinion, it might be worth going other way and bring SnowDDL up to standard of "official" products, which is the end goal anyway. I am happy to participate in [discussions](https://github.com/littleK0i/SnowDDL/discussions) and fix / improve things if necessary.

**Pull request closed without merging**
