### PR TITLE
Data engineering with ibm datastage

### PR DESCRIPTION
**Pull request by shreya-sisodia**
Updated without other removed projects, also added new title and resized images

### CODE REVIEW

**Comment by shreya-sisodia** [comment]
Hi there @iamontheinet! I made some changes to the quickstart - please let me know if everything looks alright. Thank you!

**Comment by shreya-sisodia** [comment]
Good afternoon @iamontheinet @jdanielmyers, hope you're doing well! Please let me know if there are any other blockers and I'd be happy to fix them. Thanks so much!

**Comment by shreya-sisodia** [comment]
Good morning @iamontheinet @jdanielmyers, hope you're doing well! Is there anything that needs to be fixed from my side?

**Comment by jdanielmyers** [comment]
thank you for the addition! merged!

**Pull request merged**
