### PR TITLE
Data engineering with datastage

### PR DESCRIPTION
**Pull request by shreya-sisodia**
Updating Data Engineering with DataStage Quickstart based on feedback from Paul G and team - updated images, took out "tutorial takes 20 minutes to complete" and added in trial links for DataStage and Snowflake

### CODE REVIEW

**Comment by shreya-sisodia** [comment]
@iamontheinet Good afternoon - this is the new PR. Thank you!

**Comment by iamontheinet** [comment]
@shreya-sisodia Thanks for the edits. The images are loading now :) One last request.... can you please label and format the last step like this one https://quickstarts.snowflake.com/guide/getting_started_with_snowpark_in_snowflake_python_worksheets/index.html#7?

Basically the step label should be "Conclusion and Resources" and on the content should include what you've learned, next steps, and additional resources.

Thanks again!
Dash

**Comment by shreya-sisodia** [comment]
Hi there @iamontheinet - I've reformatted the conclusion section. Thank you!

**Comment by iamontheinet** [comment]
Thanks @shreya-sisodia! The QS has been published -- https://quickstarts.snowflake.com/guide/data_engineering_with_datastage/index.html

**Pull request merged**
