### PR TITLE
Hex hol

### PR DESCRIPTION
**Pull request by Gabe-flomo**
Content for Hex + snowflakes churn model presentation at snowflake summit

### CODE REVIEW

**Comment by iamontheinet** [comment]
@Gabe-flomo Thanks for your contribution! Please make the following edits and submit a PR.

- Shorten the title to "Churn modeling using Snowflake and Hex" or "Customer Churn modeling using Snowflake and Hex"
- Add duration in minutes. Right now it's displaying "0 mins remaining" on all steps.
- Rename step "Lab overview" to "Overview"
- Remove step "Creating a Snowflake account" and add it as a prerequisite under Overview >> Prerequisites
-  Rename step "Conclusion" to "Conclusion And Resources"

Cheers,
Dash

**Comment by jdanielmyers** [comment]
I see there are merge conflicts here - is this still pr still needed or can we close?

**Comment by Gabe-flomo** [comment]
> I see there are merge conflicts here - is this still pr still needed or can we close?

I was able to resolve the conflicts 🤝🏾

**Comment by jdanielmyers** [comment]
Closing for now due to merge conflicts. Feel free to submit a new pr if needed. Thanks.

**Pull request closed without merging**
