### PR TITLE
Data Mesh Implementation with dbt Cloud

### PR DESCRIPTION
**Pull request by dpguthrie**

### CODE REVIEW

**Comment by boxysean** [comment]
Hi @iamontheinet can you please review this on Monday? This is for [MD235](https://reg.summit.snowflake.com/flow/snowflake/summit24/sessions/page/catalog/session/1709838428954001iDet) during Snowflake Summit so we need to get this in. Thanks 🙏

**Comment by iamontheinet** [comment]
@dpguthrie Thanks for creating this QS. Can you pl incorporate the following:

1. Rename the first step to "Overview" step and include "Prerequisites", "What You'll Learn" and "What You'll Build" as part of the Overview step. So basically then the "About this guide" step goes away
2. Rename the last step to "Conclusion and Resources" and include links to resources.

Refer to this QS for layout and format -- https://quickstarts.snowflake.com/guide/getting_started_with_dataengineering_ml_using_snowpark_python/index.html#0

**Comment by dpguthrie** [comment]
@iamontheinet Yep, I can finish this up today.  @boxysean fyi

**Comment by boxysean** [comment]
Hey @iamontheinet, we're ready for a re-review. Can you please do this as soon as you can? We need this merged in by Friday for Snowflake Summit event Monday. Thanks 🙏

**Comment by iamontheinet** [comment]
@dpguthrie @boxysean Thanks. I don't see "What You'll Learn" and "What You'll Build" as part of the **Overview** step and the layout of **Conclusion and Resources** isn't the same as https://quickstarts.snowflake.com/guide/getting_started_with_dataengineering_ml_using_snowpark_python/index.html#8

Is this too much of a lift for Summit? Just trying to make all guides as consistent as possible :)

**Comment by boxysean** [comment]
Hey @iamontheinet thanks for the feedback. I went back and added the sections in the [template](https://github.com/Snowflake-Labs/sfquickstarts/blob/master/site/sfguides/src/sample/sample.md). Thanks for the guidance.

Can this now please be merged so we identify any issues today before Monday's session? If you have any other feedback you would like in for longevity on quickstarts.snowflake.com, happy to work on it post-Summit.

Thank you. 🙏

**Pull request merged**
